apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-service
  labels:
    app: taxi
    type: demo
spec:
  replicas: 5
  selector:
    matchLabels:
      app: taxi
      type: demo
  template:
    metadata:
      labels:
        app: taxi
        type: demo
    spec:
      containers:
      - name: grpc-service
        image: phantruongdp/myservice:v8
        imagePullPolicy: Always
        ports:
        - containerPort: 50001
          protocol: TCP
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata: 
  name: grpc-service
spec:
  ports:
  - port: 50001
    protocol: TCP
    targetPort: 50001
  selector:
    app: taxi
    type: demo
  sessionAffinity: None
  type: LoadBalancer
