apiVersion: apps/v1
kind: Deployment
metadata:
  name: osrm-server
  labels:
    app: osm
    type: demo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: osm
      type: demo
  template:
    metadata:
      labels:
        app: osm
        type: demo
    spec:
      containers:
      - name: osrm-server
        image: peterevans/osrm-backend-k8s
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
          protocol: TCP
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata: 
  name: osrm-server
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: osm
    type: demo
  sessionAffinity: None
  type: LoadBalancer
