---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: primary-deployment2
  labels:
    name: redis-primary2
spec:
  replicas: 1 
  selector:
    matchLabels:
      name: redis-primary2
  template:
    metadata:
      labels:
        name: redis-primary2
    spec:
      subdomain: primary2
      containers:
      - name: redis2
        image: redis:5.0.4-alpine
        command:
          - "redis-server"
        args:
          - "--protected-mode"
          - "no"
        ports:
        - containerPort: 6379
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: replica-deployment2
  labels:
    name: redis-replica2
spec:
  replicas: 3 
  selector:
    matchLabels:
      name: redis-replica2
  template:
    metadata:
      labels:
        name: redis-replica2
    spec:
      subdomain: replica2
      containers:
      - name: redis2
        image: redis:5.0.4-alpine
        command:
          - "redis-server"
        args:
          - "--slaveof"
          - "primary2.default.svc.cluster.local"
          - "6379"
          - "--protected-mode"
          - "no"   
        ports:
        - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: primary2
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 6379
    targetPort: 6379
    name: redis2
  selector:
    name: redis-primary2
---
apiVersion: v1
kind: Service
metadata:
  name: replica2
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 6379
    targetPort: 6379
    name: redis2
  selector:
    name: redis-replica2
