apiVersion: apps/v1
kind: Deployment
metadata:
  name: primary-deployment1
  labels:
    name: redis-primary1
spec:
  replicas: 1 
  selector:
    matchLabels:
      name: redis-primary1
  template:
    metadata:
      labels:
        name: redis-primary1
    spec:
      subdomain: primary1
      containers:
      - name: redis1
        image: redis:5.0.4-alpine
        command:
          - "redis-server"
        args:
          - "--protected-mode"
          - "no"
        ports:
        - containerPort: 6379
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: replica-deployment1
  labels:
    name: redis-replica1
spec:
  replicas: 2 
  selector:
    matchLabels:
      name: redis-replica1
  template:
    metadata:
      labels:
        name: redis-replica1
    spec:
      subdomain: replica1
      containers:
      - name: redis1
        image: redis:5.0.4-alpine
        command:
          - "redis-server"
        args:
          - "--slaveof"
          - "primary1.default.svc.cluster.local"
          - "6379"
          - "--protected-mode"
          - "no"   
        ports:
        - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: primary1
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 6379
    targetPort: 6379
    name: redis1
  selector:
    name: redis-primary1
---
apiVersion: v1
kind: Service
metadata:
  name: replica1
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 6379
    targetPort: 6379
    name: redis1
  selector:
    name: redis-replica1
