---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: primary-deployment3
  labels:
    name: redis-primary3
spec:
  replicas: 1
  selector:
    matchLabels:
      name: redis-primary3
  template:
    metadata:
      labels:
        name: redis-primary3
    spec:
      subdomain: primary3
      containers:
      - name: redis3
        image: redis:5.0.4-alpine
        command:
          - "redis-server"
        args:
          - "--protected-mode"
          - "no"
        ports:
        - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: primary3
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 6379
    targetPort: 6379
    name: redis3
  selector:
    name: redis-primary3
